[18기 김세형] Add: 숙소 상세페이지의 RoomDetailView, ReviewView 작성, test 완료
wecode-bootcamp-korea/18-2nd-AirDropTheBeat-backend pull request #6
Opened 2021-04-05 14:50 UTC by sehyeongkim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- RoomDetailView 작성
- ReviewView 작성
- tests.py 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- RoomDetailView에서는 room_id는 path parameter 형식으로, 나머지 check_in(체크인 날짜), check_out(체크아웃 날짜), adults,child,baby(인원 수) 값들은 query parameter 형식으로 받아서 view 로직을 작성했습니다.
- ReviewView에서는 aggregate의 Avg로 평균값을 계산했습니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-04-05 14:52 UTC, sehyeongkim commented
- 테스트 성공
<img width="913" alt="스크린샷 2021-04-05 오후 11 36 00" src="https://user-images.githubusercontent.com/75714292/113587559-eb661380-9669-11eb-9956-92406fa79f2a.png">

2021-04-05 14:55 UTC, sehyeongkim commented
- RoomDetailView
<img width="1004" alt="스크린샷 2021-04-05 오후 11 52 44" src="https://user-images.githubusercontent.com/75714292/113587630-059ff180-966a-11eb-8df5-650d20b54e71.png">
<img width="1003" alt="스크린샷 2021-04-05 오후 11 54 07" src="https://user-images.githubusercontent.com/75714292/113587763-3849ea00-966a-11eb-873f-d3f312aa832d.png">
<img width="990" alt="스크린샷 2021-04-05 오후 11 54 42" src="https://user-images.githubusercontent.com/75714292/113587809-4b5cba00-966a-11eb-8e6d-5ac94c7ed35f.png">

- ReviewView
<img width="1013" alt="스크린샷 2021-04-05 오후 11 55 15" src="https://user-images.githubusercontent.com/75714292/113587871-5fa0b700-966a-11eb-837a-10cbc8ae738d.png">
<img width="1012" alt="스크린샷 2021-04-05 오후 11 55 35" src="https://user-images.githubusercontent.com/75714292/113587904-6af3e280-966a-11eb-816e-28acc050ba56.png">

2021-04-06 01:05 UTC, ulfrid requested changes
확인 바랍니다~!

2021-04-06 01:05 UTC, devops-andrew commented on room/views.py
> +    def get(self, request, room_id):
room_id 를 받는데, validation 체크가 없네요. 없는 room_id가 들어올 경우 500 에러날것 같아요~
체크해주시고, 테스트 추가해주세요~!

2021-04-06 01:05 UTC, devops-andrew commented on room/views.py
> +        images = Image.objects.filter(room=room)
이부분 사실 한번에 접근 가능한데, 아래에 결과를 작성할때  room 하나만 알았다면 이미 전부 접근 가능한 상황인데, 위의 host나 images는 불필요하다는 점입니다. 보다 장고 쿼리셋을 잘 활용해서  변경하셨으면 좋겠습니다.

2021-04-06 17:51 UTC, sehyeongkim commented on room/views.py
> +        images = Image.objects.filter(room=room)
변경했습니당

2021-04-06 17:53 UTC, sehyeongkim commented on room/views.py
> +    def get(self, request, room_id):
list 에서 클릭해서 들어오는 detail 페이지라서 없는 room id는 따로 고려 안해줘도 될 것 같았는데 아닐까요?
사용자가 url를 임의로 변경했을 때 발생가능한 에러인 것 같네요 ...!
리뷰 반영하여 수정했습니다~!

2021-04-06 18:03 UTC, sehyeongkim commented on room/views.py
> +        images = Image.objects.filter(room=room)
대체 무슨 생각으로 저 코드를 작성한건지 모르겠네요.. 🧐

2021-04-07 01:47 UTC, ulfrid commented on room/views.py
> +    def get(self, request, room_id):
넵~! 우리는 항상 최악을 대비해야 합니다. ㅋㅋ

2021-04-07 01:51 UTC, ulfrid requested changes
확인해 주세요~!

2021-04-07 01:51 UTC, ulfrid commented on room/views.py
> +                "images_url": [image.image_url for image in Image.objects.filter(room=room)],
이것도 
```suggestion
                "images_url": [image.image_url for image in room.image_set.all()],
```
이렇게 하면 되지 않을까요?

2021-04-07 14:17 UTC, ulfrid commented
LGTM 👍

2021-04-07 14:17 UTC, merged